application: typing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets
- url: .*
  script: typing.app

libraries:
- name: webapp2
  version: "2.5.2"
